services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      FRONT_ORIGIN: http://localhost:3000   # origine du front autorisée
    volumes:
      - app-data:/data                      # conserve data.json
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  app-data:
